name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.12.2
          run_install: true
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - name: Build zig wasm
        run: pnpm build:resources
      - name: Build and zip extension artifact
        run: pnpm build:plasmo --zip
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@staging
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
          verbose: true
